return {
  "xiyaowong/transparent.nvim",
  "udalov/kotlin-vim",
  "nyoom-engineering/oxocarbon.nvim",
  { "akinsho/toggleterm.nvim", version = "*", config = true },
  "elkowar/yuck.vim",
  {
    "lervag/vimtex",
    tex_flavor = "latex",
    vimtex_view_method = "zathura",
    vimtex_quickfix_mode = 0,
    conceallevel = 1,
    tex_conceal = "abdmg",
    vimtex_compiler_method = "latexrun",
  },
  "dense-analysis/ale",
  "ap/vim-css-color",
  "sheerun/vim-polyglot",
  "mattn/emmet-vim",
  "eraserhd/parinfer-rust",
  "lambdalisue/fern.vim",
  "nvim-telescope/telescope.nvim",
  "folke/zen-mode.nvim",
}
